/*
 * Vogon personal finance/expense analyzer.
 * License TBD.
 * Author: Dmitry Zolotukhin <zlogic@gmail.com>
 */
package org.zlogic.vogon.ui;

import java.io.File;
import java.text.MessageFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.zlogic.vogon.data.CsvImporter;
import org.zlogic.vogon.data.FinanceData;

/**
 *
 * @author Zlogic
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
	initComponents();
	//Restore settings
	lastDirectory= preferenceStorage.get("lastDirectory", null)==null?null:new java.io.File(preferenceStorage.get("lastDirectory", null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle"); // NOI18N
        setTitle(bundle.getString("MAINWINDOW_TITLE")); // NOI18N
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setModel(new org.zlogic.vogon.ui.TransactionsTableModel());
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        jTabbedPane1.addTab(bundle.getString("TRANSACTIONS"), jPanel1); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jTable2.setModel(new org.zlogic.vogon.ui.AccountsTableModel());
        jTable2.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);

        jTabbedPane1.addTab(bundle.getString("ACCOUNTS"), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1);

        jMenuFile.setText(bundle.getString("FILE")); // NOI18N

        jMenuItemImport.setText(bundle.getString("IMPORT...")); // NOI18N
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemImport);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
	// Prepare file chooser dialog
	JFileChooser fileChooser = new JFileChooser((lastDirectory!=null && lastDirectory.exists())?lastDirectory:null);
	fileChooser.setMultiSelectionEnabled(false);
	fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
	fileChooser.setDialogTitle(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("CHOOSE_FILES_TO_IMPORT"));
	//Prepare file chooser filter
	fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("CSV_FILES_(COMMA-SEPARATED)"), "csv")); //NOI18N
	if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
	    File selectedFile = fileChooser.getSelectedFile();
	    lastDirectory = selectedFile.isDirectory() ? selectedFile : selectedFile.getParentFile();
	    preferenceStorage.put("lastDirectory", lastDirectory.toString());

	    //Test code for printing data
	    CsvImporter importer = new CsvImporter();
	    try {
		FinanceData financeData = importer.importFile(selectedFile);
		((TransactionsTableModel) jTable1.getModel()).setFinanceData(financeData);
		((AccountsTableModel) jTable2.getModel()).setFinanceData(financeData);
	    }catch (org.zlogic.vogon.data.VogonImportLogicalException e) {
		JOptionPane.showMessageDialog(this, new MessageFormat(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT_EXCEPTION_DIALOG_TEXT")).format(new Object[]{e.getLocalizedMessage(), org.zlogic.vogon.data.Utils.getStackTrace(e)}), java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT_EXCEPTION_DIALOG_TITLE"), JOptionPane.ERROR_MESSAGE);
	    } catch (Exception e) {
		JOptionPane.showMessageDialog(this, new MessageFormat(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT_EXCEPTION_DIALOG_TEXT_STACKTRACE")).format(new Object[]{e.getLocalizedMessage(), org.zlogic.vogon.data.Utils.getStackTrace(e)}), java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT_EXCEPTION_DIALOG_TITLE"), JOptionPane.ERROR_MESSAGE);
	    }
	}
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) { //NOI18N
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    @Override
	    public void run() {
		new MainWindow().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
    private File lastDirectory = null;
    protected java.util.prefs.Preferences preferenceStorage = java.util.prefs.Preferences.userNodeForPackage(MainWindow.class);
}
