/*
 * Vogon personal finance/expense analyzer.
 * License TBD.
 * Author: Dmitry Zolotukhin <zlogic@gmail.com>
 */
package org.zlogic.vogon.ui;

import java.io.File;
import java.text.MessageFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.zlogic.vogon.data.CsvImporter;
import org.zlogic.vogon.data.FinanceData;
import org.zlogic.vogon.data.Utils;

/**
 *
 * @author Zlogic
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle"); // NOI18N
        jMenuFile.setText(bundle.getString("FILE")); // NOI18N

        jMenuItemImport.setText(bundle.getString("IMPORT...")); // NOI18N
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemImport);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
	// Prepare file chooser dialog
	JFileChooser fileChooser = new JFileChooser(lastDirectory);
	fileChooser.setMultiSelectionEnabled(false);
	fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
	fileChooser.setDialogTitle(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("CHOOSE FILES TO IMPORT"));
	//Prepare file chooser filter
	fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("CSV FILES (COMMA-SEPARATED)"), "csv"));
	if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
	    File selectedFile = fileChooser.getSelectedFile();
	    lastDirectory = selectedFile.isDirectory() ? selectedFile : selectedFile.getParentFile();

	    //Test code for printing data
	    CsvImporter importer = new CsvImporter();
	    try {
		FinanceData financeData = importer.importFile(selectedFile);
		financeData.printTransactions();
	    } catch (Exception e) {
		JOptionPane.showMessageDialog(this, new MessageFormat(java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT EXCEPTION DIALOG TEXT")).format(new Object[]{e.getLocalizedMessage()}), java.util.ResourceBundle.getBundle("org/zlogic/vogon/ui/Bundle").getString("IMPORT EXCEPTION DIALOG TITLE"), JOptionPane.ERROR_MESSAGE);
	    }
	}
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    @Override
	    public void run() {
		new MainWindow().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemImport;
    // End of variables declaration//GEN-END:variables
    private File lastDirectory = null;
}
